alias ls="ls --color=auto"
alias ll="ls -alh"
alias l="ls -lh"

alias ..="cd .."
alias ...="cd ../.."
alias ....="cd ../../.."
alias .....="cd ../../../.."

alias gcl="git clone"
alias gs="git status"
alias gd="git diff"
alias ga="git add"
alias gal="git add ."
alias gbr="git branch"
alias gch="git checkout"
alias gchp="git cherry-pick"
alias gf="git fetch"
alias gt="git tag"
alias grs="git reset"
alias grv="git revert"
alias gcm="git commit -m"
alias gm="git merge"
alias gr="git rebase"
alias gu="git pull origin"
alias gp="git push origin"
alias gl="git log --oneline"
alias gsh="git stash"
alias gshp="git stash pop"
alias gshl="git stash list"
alias gshs="git stash save"
alias gsha="git stash apply"

alias untar="tar -zxvf"
alias listar="tar -tzf"

alias dcl="docker-clean"
alias dpr="docker system prune -a -f"
alias dli="docker images -a"
alias dlc="docker ps -a"
alias dlv="docker volume ls"

alias upd="sudo pacman -Syu --noconfirm && paru -Sua --noconfirm"
alias key_upd="sudo pacman -Sy archlinux-keyring && pacman -Su"
alias orphans="sudo pacman -Qtdq | sudo pacman -Rns -"

alias rss="newsboat"
alias rr="ranger"
alias e="$EDITOR"
alias v="$VISUAL"
alias epub="mupdf -U ~/epub-styles.css"
alias myip="curl ipinfo.io/ip"
alias shownet="nmcli -t -f name connection show --active"
alias wr="curl wttr.in/?format='%l:+%C+%t\n'"
alias moon="curl wttr.in/Moon"
alias space="df -h"
alias vpn="sudo openvpn --config"
alias showip="ip addr show wlan0"
alias vpn_import="sudo nmcli connection import type wireguard file ~/vishnyakova.conf"
