background {
    monitor =
    path = ~/Wallpapers/wallhaven-m9rrmk_9408x5292.png
    blur_passes = 1
    contrast = 1
    brightness = 0.8
    vibrancy = 0.1
    vibrancy_darkness = 0.1
}

general {
    ignore_empty_input = true
}

input-field {
    monitor =
    size = 250, 60
    outline_thickness = 2
    dots_size = 0.2 # Scale of input-field height, 0.2 - 0.8
    dots_spacing = 0.2 # Scale of dots' absolute size, 0.0 - 1.0
    dots_center = true
    outer_color = rgba(0, 0, 0, 0)
    inner_color = rgba(0, 0, 0, 0.5)
    font_color = rgb(200, 200, 200)
    fade_on_empty = false
    font_family = Fira Sans Medium
    placeholder_text = <i><span foreground="##cdd6f4">Input Password...</span></i>
    hide_input = false
    position = 0, -120
    halign = center
    valign = center
}

label {
    monitor =
    text = $TIME
    color = $foreground
    font_size = 120
    font_family = Fira Sans Medium
    position = 0, -300
    halign = center
    valign = top
}
