require'nvim-treesitter.configs'.setup {
  ensure_installed = {
	  'c',
	  'clojure',
	  'gitignore',
	  'gitattributes',
	  'gitcommit',
	  'git_config',
	  'git_rebase',
	  'cpp',
	  'lua',
	  'go',
	  'javascript',
	  'css',
	  'bash',
	  'html',
	  'json',
	  'jsdoc',
	  'python',
	  'scss',
	  'solidity',
	  'tsx',
	  'typescript',
	  'vim',
	  'vue',
	  'xml',
	  'yaml',
	  'toml',
	  'svelte',
	  'graphql',
	  'dockerfile',
	  'elixir',
	  'markdown',
	  'pug',
	  'todotxt',
	  'php',
	  'comment',
	  'nginx',
	  'sql',
	  'editorconfig',
	  'angular',
  },
  sync_install = false,
  highlight = {
    enable = true,
    additional_vim_regex_highlighting = false,
  },
  indent = {
    enable = false,
  },
  autotag = {
    enable = true,
  },
}

vim.opt.foldmethod = 'expr'
vim.opt.foldexpr = 'nvim_treesitter#foldexpr()'
